jquery_lang_js.prototype.lang.es = {
"4G LTE Smart USB Modem":"4G LTE Smart USB Modem",
"Save":"Guardar",
"OK":"OK",
"Cancel":"Cancelar",
"Saved!":"Guardado!",
"Failed!":"Fallado!",
"On":"Prendido",
"Off":"Apagado",
"Not Activated":"No Activado",
"Connecting...":"Conectando",
"Disconnecting...":"Desconectando",
"Connected":"Conectado",
"Disconnected":"Desconectado",
"No Service":"Sin Servicio",
"GSM":"GSM",
"WCDMA":"WCDMA",
"LTE":"LTE",
"Connect":"Conectar",
"Disconnect":"Desconectar",
"3G Unavailable":"3G No Disponible",
"3G Network":"Red de 3G",
"3G Available":"3G Disponible",
"4G LTE Unavailable":"LTE 4G No Disponible",
"4G LTE Network":"Red de 4G LTE",
"4G LTE Available":"LTE 4G No Disponible",
"Signal:":"Señal:",
"Device &amp; Network":"Dispositivo &amp; Red",
"General Device &amp; Network Information":"Dispositivo General &amp; Información de la Red",
"General Device":"Dispositivo General",
"Device Name":"Nombre del Dispositivo",
"Device Description":"Descripción del Dispositivo",
"Manufacturer":"Manufacturero",
"Modem Model":"Nombre del Modelo",
"Hardware Version":"Verisión del Hardware",
"Firmware Version":"Versión del Firmware",
"General Network":"Red General",
"IP Address":"Dirección del IP",
"Gateway":"Gateway",
"DNS Server":"Servidor DNS",
"Data Received":"Mensaje Recibido",
"Data Sent":"Mensaje Enviado",
"Data Total":"Mensaje Total",
"4G LTE Device &amp; Network Information":"Dispositivo 4G LTE &amp; Información de la Red",
"4G LTE Device":"Dispositivo de 4G LTE",
"Technology":"Tecnología",
"USIM State":"Estado de USIM",
"4G LTE Network":"Red de 4G LTE",
"Status":"Estatus",
"3G Device &amp; Network Information":"Dispositivo 3G &amp; Información de la Red",
"3G Device":"Dispositivo de 3G",
"PRL version":"Versión de PRL",
"3G Network":"Red de 3G",
"Check Usage":"Verificar Uso",
" has been used":"Ha sido Usada",
"Jan":"Ene",
"Feb":"Feb",
"Mar":"Mar",
"Apr":"Abr",
"May":"May",
"Jun":"Jun",
"Jul":"Jul",
"Aug":"Ago",
"Sep":"Sep",
"Oct":"Oct",
"Nov":"Nov",
"Dec":"Dic",
"Since":"Desde",
"Would you like to reset usage data?":"Le gustaría volver a empezar el uso de datos?",
"Timestamp":"Fecha y Hora",
"Duration(total)":"Duración (Total)",
"Duration(active)":"Duración (Activo)",
"Rx":"Rx",
"Received":"Recibido",
"Tx":"Tx",
"Transmitted":"Transmitido",
"Total Num":"Número Total",
"Wi-Fi":"Wi-Fi",
"Wi-Fi Profiles":"Perfil de Wi-Fi",
"Network Name (SSID)":"Nombre de la Red (SSID)",
"802.11 Mode":"Modo 802.11",
"Channel":"Canal",
"Security":"Seguridad",
"Security Option":"Opción de Seguridad",
"WPA Passphrase":"WPA Passphrase",
"Input Type":"Tipo de Entrada",
"Connected Devices":"Dispositivos Conectados",
"Mac Address":"Dirección de Mac",
"Host Name":"Nombre de Host",
"Expires in":"Expira en",
"&nbsp;Key length is 5 ASCII characters.":"&nbsp; Longitud de la clave son 5 caracteres ASCII",
"&nbsp;Key length is 13 ASCII characters.":"&nbsp; Longitud de la clave son 13 caracteres ASCII",
"&nbsp;Key length is 10bytes key in hexadecimal.":"&nbsp; Longitud de la clave son 10bytes en hexadecimal.",
"&nbsp;Key length is 26bytes key in hexadecimal.":"&nbsp; Longitud de la clave son 26bytes en hexadecimal.",
"&nbsp;Key length is 8~63 ASCII characters.<br>&nbsp;For greater security, use a mixture of digits,<br>&nbsp;upper case, lower case and other symbols.":"&nbsp; Longitud de la clave son de 8-63 caracteres ASCII. <br>&nbsp; Para mas seguridad mezcle los dígitos<br>&nbsp; mayúsculas, minúsculas y otros símbolos",
"Rebooting your device is needed.<br>Then you need to try again to connect.<br>Do you want to continue?":"Es necesario reiniciar su dispositivo.<br> Luego vuelva a intentar a conectarse.<br>Desea continuar?",
"Password length range is 8~63 ASCII characters.":"Longitud de la contraseña son de 8-63 caracteres ASCII",
"SSID is including invalid characters[\\]":"El SSID incluye caracteres inválidos",
"SSID is EMPTY":"El SSID está vacío",
"SSID MAX length is 32 characters":"Máxima longitud de SSID son de 32 caracteres",
"Password length is 10h(5c) or 26h(13c)":"Longitud de la contraseña son 10h(5c) o 26h(13c)",
"Invalid Hex Values":"Valores de Hex Inválidos",
"Password length range is 8~63 ASCII characters.":"Longitud de la contraseña son de 8-63 caracteres ASCII",
"Invalid Security Option":"Opción de Seguridad Inválida",
"IP Address is invalid":"Dirección de IP es Inválida",
"Subnet Mask is invalid":"Subnet Mask es Inválido",
"Start DHCP Address Range is invalid":"Gama de direccion Start DHCP es Inválido",
"End DHCP Address Range is invalid":"Gama de direccion End  DHCP es Inválido",
"Custom DNS Address is empty.<br>Please set at least one of Custom DNS.":"Dirección Personalizada de DNS está vacía.<br> Por favor personalize un DNS.",
"Custom Primary DNS Address is invalid":"Dirección Principal personalizada de DNS es inválida",
"Custom Secondary DNS Address is invalid":"Dirección Secundaria personalizada de DNS es inválida",
"Settings":"Ajustes",
"Connection Options":"Opciones de Conexión",
"Enable Airplane Mode":"Permitir Modo de Avión",
"Enable Auto Connection":"Permitir Auto Conexión",
"Automatic":"Automático",
"4G LTE Only":"Sólo 4G LTE",
"3G Only":"Sólo 3G",
"LAN Setting":"Ajustes de LAN",
"IP Address":"Direccion de IP",
"Subnet Mask":"Subnet Mask",
"Enable DHCP Server":"Habilitar Sevidor de DHCP",
"Start DHCP Address Range":"Gama de dirección Start DHCP",
"End DHCP Address Range":"Gama de dirección End  DHCP",
"Custom DNS":"DNS personalizada",
"Enable Custom DNS":"Habilitar DNS personalizada",
"Custom Primary DNS Address":"Dirección Principal Personalizada de DNS",
"Custom Secondary DNS Address":"Dirección Secundaria Personalizada de DNS",
"Advanced Settings":"Ajustes Avanzados",
"General Settings":"Ajustes Generales",
"LED Control":"Control de LET",
"Disable LED":"Deshabilitar LED",
"Advanced Settings Password":"Contraseña de Ajustes Avanzados",
"Original Password(Default is admin)":"Contraseña Original (Por defecto es admin)",
"New Password":"Nueva Contraseña",
"Confirm New Password":"Confirmar la Nueva Contraseña",
"Password successfully changed!":"La Contraseña ha sido modificada!",
"New password not set.":"Sin Contraseña nueva",
"Password do not match.":"No coincide la contraseña",
"Internal error please try again.":"Error interno, por favor vuelva a intentar",
"You can't change the password.":"No puede cambiar la contraseña",
"The user name is incorrect.":"El Nombre de usuario es incorrecto",
"The password is incorrect.":"La contraseña es incorrecta",
"Manual Configuration":"Configuración manual",
"LTE Profile":"Perfil de LTE",
"WCDMA Profile":"Perfil de WCDMA",
"GSM Profile":"Perfil de GSM",
"APN name":"Nombre de APN",
"Profile name":"Nombre de perfil",
"Authentication Preference":"Preferencia de Autenticacion",
"Username":"Nombre  de Usuario",
"Updates":"Actualizaciones",
"Automatic Version Check":"Comprobacion Automatica de Versiones",
"Enable notification":"Notificacion Habilitada",
"Check System Upgrade":"Comprobar Actualizacion de Sistema",
"Current Software Version":"Version Actual del Software",
"Newest Software Version":"Version de Software mas Reciente",
"SW update is available. Would you like to download now?":"SW actualización disponible. ¿Desea descargarla ahora?",
"No SW update available":"No actualización de software disponible",
"Check Now":"Comprobar ahora",
"Software Update":"Actualizacion de Software",
"Update software to device":"Actualización de software en el dispositivo",
"Engineering":"Ingeniería",
"System Log Settings":"Configuración del registro del sistema",
"Sets the local log level of messages :":"Establece el nivel de registro local de los mensajes:",
"Max size (KB) before rotate(1~500) :":"Max tamaño (KB) antes de rotar (1 ~ 500):",
"Number of rotated logs to keep(1~10) :":"Número de registros para mantener girado (1 ~ 10):",
"System Logs":"Registros del sistema",
"Export to Desktop":"Exportar al escritorio",
"Refresh":"Actualizar",
"Clear Log":"Borrar registro",
"Equipment":"Equipo",
"Refurbish":"Restaurado",
"Factory Reset":"Restablecimiento de fábrica",
"Reset":"Reinicializar",
"Debug":"Limpiar",
"Refresh Rate(Seconds) :":"Actualización de Proporcion (segundos):",
"Common":"Común",
"Current Service":"Servicio Actual",
"Signal Strength":"Intensidad de la señal",
"Roaming Indicator":"Indicador de roaming",
"Last Error Code":"Último código de error",
"Serving Cell":"Sirviendo celular",
"Band":"Banda",
"State":"Estado",
"UL Channel":"Canal UL",
"DL Channel":"Canal DL",
"Tx Power":"Poder Tx",
"Error Rate":"Estado de Error",
"Version":"Version",
"Help":"Ayuda",
"About":"Acerca de",
"System Name":"Nombre de Sistema",
"Franklin 3G/4G Connection Manager":"Franklin 3G/4G Connection Manager",
"CM Version":"Versión CM",
"User Guide":"Guia del Usuario",
"Absent":"Ausente",
"Present":"Presente",
"Error":"Error",
"Would you like to log out now?":"¿Te gustaría salir ahora?",
"Yes":"Si",
"No":"No",
"Administrator":"Administrador",
"Log Out":"Salir",
"Password":"Contraseña",
"Default password: admin":"Contraseña por defecto: admin",
"MSL code required":"MSL código necesario",
"Sorry, the MSL is incorrect.<br>Please try again.":"Lo sentimos, el MSL es incorrecto.<br>Por favor, inténtelo de nuevo.",
"Administrator Login Required":"Administrador de Inicio de sesión obligatorio",
"Your session may expired.<br>Please login again.":"Su sesión puede expirado. Por favor, ingresa de nuevo.",
"Sorry, the Administrator password is incorrect.<br>Please try again.":"Lo sentimos, la contraseña del administrador es incorrecta.<br>Por favor, inténtelo de nuevo.",
"Sorry, the web site is busy.<br>Please try again later.":"Lo sentimos, la página web es busy.<br>Please inténtelo de nuevo más tarde.",
"Sorry, there is already an online administrator.":"Lamentablemente ya hay un administrador en línea.",
"You have no authority please login as an administrator.":"No tienes ninguna autoridad, por favor entra de nuevo  como administrador.",
"Sorry, there is already an online user from CLI.":"Lamentablemente ya hay un usuario conectado desde CLI.",
"Set as default":"Establecer por defecto",
"Edit":"Editar",
"Add":"Añadir",
"Delete":"Borrar registro",
"Can NOT delete a default profile!":"No se puede eliminar un perfil predeterminado!",
"Profiles":"Perfiles",
"2G/3G Device &amp; Network Information":"Dispositivo 2G/3G &amp; Información de la Red",
"2G/3G Device":"Dispositivo de 2G/3G",
"2G/3G Network":"Red de 2G/3G",
"2G Only":"Sólo 2G",
"2G/3G Unavailable":"2G/3G No Disponible",
"2G/3G Network":"Red de 2G/3G",
"2G/3G Available":"2G/3G Disponible",
"Activate":"Activar",
"No Signal":"No hay señal",
"Airplane Mode":"Modo Avión",
"Network Search":"Red de búsqueda",
"Automatic search":"Búsqueda Automática",
"Manual search":"Búsqueda Manual",
"Operator":"Operador",
"Network type":"Tipo de red",
"Status":"Estatus",
"Available":"Disponible",
"Serving":"Servicio",
"Unknown":"Desconocido",
"Search":"Busqueda",
"Select":"Seleccionar",
"Connection Options will change to '3G Only' mode.":"Opciones de conexión cambiará a '3G Only'.",
"Connection Options will change to '2G Only' mode.":"Opciones de conexión cambiará a '2G Only'.",
"Connection Options will change to '4G LTE Only' mode.":"Opciones de conexión cambiará a '4G LTE Only'.",
"Searching...":"Búsqueda",
"This may take a few moments.":"Este proceso puede tardar unos minutos…",
"Telcel Number: ":"Número Telcel: ",
"iTelcel":"iTelcel",
"My Telcel":"Mi Telcel",
"MSNGR":"MSNGR",
"Plugger":"Plugger",
"Statistics":"Estadisticas",
"Configuration":"Configuración",
"The webpage will refresh because the system may be rebooted.":"La página web se actualizará debido a que el sistema puede ser reiniciado.",
"Your Telcel Connection Manager has determined that 3G will provide the best connection at this time.  Do you want to connect to 3G now?":"Su Administrador de conexión Telcel 3G ha determinado que proporcionará la mejor conexión en este momento. ¿Desea conectarse a 3G ahora?",
"DO NOT REMOVE YOUR USB DEVICE FROM THE COMPUTER WHILE THIS MESSAGE IS DISPLAYED":"NO REMUEVA EL DISPOSITIVO USB de SU COMPUTADORA MIENTRAS SE MUESTRA ESTE MENSAJE",
"Important Notice:":"Aviso Importante:",
"Your USB device is applying new software or service settings.  This may take a few minutes.":"El dispositivo USB está aplicando un nuevo software o configuración en el servicio. Este proceso puede tardar unos minutos.",
"It is very important that the device remain in the computer's USB port during this operation.  It is best to plug your computer into a wall outlet at this time to reduce the risk of losing power during this operation.":"Es muy importante que el dispositivo permanezca en el puerto USB de su computadora durante esta operación. Lo mejor es conectar la computadora a una toma de corriente en este momento para reducir el riesgo de perder el poder durante esta operación.",
"Telcel Network Logon Credentials":"Credenciales Telcel para inicio de sesión de red",
"Enter username and password that will be used to logon on to your network.":"Ingrese nombre de usuario y contraseña que se usará para iniciar sesión en su red.",
"Username         (Permanently Stored)":"Nombre de usuario (almacenado permanentemente)",
"Password         (Permanently Stored)":"Contraseña (permanentemente almacenado)",
"Information":"información",
"Please wait until NMEA is enabled.":"Por favor espere hasta NMEA está habilitado.",
"Please wait until NMEA is disabled.":"Por favor espere hasta NMEA está desactivada.",
"Message screen will close automatically after NMEA is enabled.":"Pantalla de mensaje se cerrará automáticamente después de que NMEA sea habilitado.",
" NOTE: ":"AVISO :",
"If the NMEA driver does not automatically install, please proceed to the TelcelCD drive under My Computer for manual install.":"Si el controlador NMEA no se instala automáticamente, diríjase por favor a la unidad TelcelCD en Mi PC para la instalación manual.",
"Fail to enable IPPT":"Fallo al permitir IPPT",
"Fail to disable IPPT":"Fallo al desactivar IPPT",
"Fail to enable NMEA":"Fallo al permitir NMEA",
"Fail to disable NMEA":"Fallo al desactivar NMEA",
"This message will close automatically.":"Este mensaje se cerrará automáticamente.",
"NMEA is only supported on Windows.":"NMEA sólo es compatible con Windows.",
"Datalink will be enabled and webpage will be reload !!":"Datalink se activará y la página web se recargara!",
"Continue?":"¿Desea continuar?",
"Please wait until switching is completed.":"Por favor, espere hasta que se complete el cambio.",
"Handover to better service...":"Traspaso a un mejor servicio ...",
"SW update is available. Would you like to download now?":"SW actualización disponible. ¿Desea descargarla ahora?",
"Please wait until IPPT is enabled. ":"Por favor, espere hasta que IPPT está habilitado.",
"Please wait until IPPT is disabled. ":"Por favor, espere hasta que IPPT está desactivado.",
"As IPPT is Enabled, your web connection will be lost for a few seconds.":"Cuando IPPT está activado, la conexión a Internet se pierde durante unos segundos.",
"Datalink will be disabled and webpage will be reload !!":"Datalink se desactivará y la página web se recarga!",
"Currently data is connected, or 3G radio is off. ":"Actualmente, datos está conectado, o radio 3G está apagado.",
"do you want to disconnect or turn 3G radio on and proceed?":"¿quieres desconectar o apagar la radio 3G y proceder?",
"Airplane mode is enabled. ":"Modo avión está activado.",
"Please try again after unchecking 'Enable Airplane Mode'.":"Por favor, inténtelo de nuevo después de desmarcar 'Habilitar el modo de avión'.",
"Currently data is not connected. ":"Actualmente  datos no están conectados.",
"Please try to connect the network!":"Por favor, intente conectarse a la red!",
"Please wait ...":"Por favor, espere ...",
"Scanning for networks. Please wait...":"Escaneo de redes. Por favor, espere ...",
"You are about to establish a data connection on an internatinal roaming network outside the U.S., Puerto Rico, and U.S. Virgin Islands. International roaming charges apply per your service plan options. Certain data usage limits apply per your service plan agreement.":"Usted está a punto de establecer una conexión de datos en una red Internacional de raoming fuera de los EE.UU., Puerto Rico y las Islas Vírgenes de los EE.UU.. Tarifas de roaming Internacional se aplicaran de acuerdo a sus opciones del plan de servicio. Ciertos límites de uso del servicio de datos aplican a su contrato de plan de servicio.",
"You currently do not have International Roaming enabled. Please make sure you have International setup on your Telcel account and the Hostless CM.":"Actualmente NO tiene habilitado roaming Internacional. Por favor, asegúrese de que tiene la configuración internacional en su cuenta de Telcel y el CM Hostless.",
"There was a problem trying to connect. Please retry. If the problem persists, contact Telcel Customer Support Center.":"Hubo un problema al intentar conectarse. Por favor, inténtelo de nuevo. Si el problema persiste, póngase en contacto con el Centro de atención al cliente de Telcel.",
"There was a problem trying to connect to the Telcel Network. ":"Hubo un problema al intentar conectarse a la red de Telcel.",
"If you have an active Telcel Mobile Broadband Device account, please retry. If this is a recycled device, has previously been activated, or used with a Day Pass, press Reset. If the problem persists, contact Telcel Customer Support Center.":"Si usted tiene una cuenta activa Telcel Mobile dispositivo de banda ancha, por favor, inténtelo de nuevo. Si se trata de un dispositivo de reciclado, ya ha sido activado, o se utiliza con un pase diario, pulse en Restablecer. Si el problema persiste, póngase en contacto con el Centro de atención al cliente de Telcel.",
"This operation will restore all settings back to factory default, continue?":"Esta operación restaurará todos los ajustes a los valores predeterminados de fábrica, continuar?",
"The device is now rebooting... <br>Reconnect to the WiFi hotspot and refresh your browser after the device reboots.":"El dispositivo ya está reiniciando ... MedlinePlus Volver a conectar el punto de acceso WiFi y actualizar su navegador después de reiniciar el dispositivo.",
"The restore process has completed successfully.":"El proceso de restauración se ha completado con éxito.",
"You will be redirected momentarily.":"Usted será redirigido momentáneamente.",
"Activation Information":"Activación de la Información",
"Error : Password length is 0 ! <br>Try it again!":"Error : la longitud de la contraseña es 0 ! <br>Inténtalo de nuevo!",
"Try it again!":"Inténtalo de nuevo!",
"Please try to disconnect the network!":"Por favor, intenta desconectar de la red!",
"Service is not activated":"El servicio no está activado",
"Service is activated":"Servicio está activado",
"Activation is not available in 4G LTE network.":"La activación no está disponible en la red 4G LTE.",
"If you want to activate the device, please change the connection mode to 3G Only!":"Si desea activar el dispositivo, cambie el modo de conexión a 3G Only!",
"Network does not respond":"Red no responde",
"Service is already activated":"El servicio se ha activado",
"Activation is not completed":"La activación no se ha completado",
"Deleted!":"Borrado!",
"USIM PIN Lock":"Bloqueo del PIN USIM",
"Enable PIN Lock":"Activar Bloqueo PIN",
"PIN Code":"Código PIN",
"Original PIN Code":"Código PIN original",
"New PIN Code":"Nuevo código PIN",
"Confirm New PIN Code":"Confirme el nuevo código PIN",
"PIN code not set.":"Código PIN no establecido.",
"PIN code do not match.":"Código PIN no coinciden.",
"Sorry, the PIN code is incorrect.<br>Please try again.":"Lo sentimos, el código PIN es incorrecto.<br>Por favor, inténtelo de nuevo.",
"Sorry, PIN retries is exceeded or incorrect<br>Please try again.":"Lo sentimos, reintentos del PIN se supera o es incorrecto.<br>Por favor, inténtelo de nuevo.",
"Enter PIN code":"Introducir código PIN",
"PUK retries is exceeded. Please contact network operator or service!":"PUK retries is exceeded. Please contact network operator or service!",
"Enter New PIN code":"Introduzca el nuevo código PIN",
"Enter PUK code":"Introduzca el nuevo código PUK",
"times":"Veces",
"en":"es",
"Failed to change PIN Code!":"No se ha podido cambiar el código PIN!",
"Original PIN code not set.":"Original PIN code not set.",
"New PIN code not set.":"Código PIN nuevo no establecido.",
"New PIN code do not match.":"Nuevo código PIN no coinciden.",
"Lock":"Bloquear",
"time remained":"Vez Sobrante",
"times remained":"Veces Sobrantes",
"PIN code is incorrect.<br>Please try again.":"Código PIN es incorrecto. <br>Por favor, inténtelo de nuevo.",
"PIN retries is exceeded":"Reintentos de PIN excedidos",
"PIN code is not set.<br>Please try again.":"Código PIN no se ha establecido. <br>Por favor, inténtelo de nuevo.",
"PUK code is not set.<br>Please try again.":"Código PUK no se ha establecido. <br>Por favor, inténtelo de nuevo.",
"PUK code is not a valid value.<br>Please try again.":"El código PUK no es válido. <br>Por favor, inténtelo de nuevo.",
"PIN is blocked. Please contact your network operator or service!":"PIN está bloqueado. Por favor, póngase en contacto con su operador de red o servicio!",
"Network Settings":"Configuración de red",
"LAN Settings":"Configuración de LAN",
"Subnet Mask":"Subred de Mask",
"Security Settings":"Configuración de seguridad",
"Port Forwarding":"Reenvío de puertos",
"Port Forwarding Configuration":"Configuración de puerto de reenvíos",
"Protocol":"Protocolo",
"External Port":"Puerto Externo",
"Internal Port":"Puerto Interno",
"Comment":"Comentario",
"Action":"Accion",
"FireWall":"Servidor de Seguridad",
"Packet Filtering Configuration":"Filtrado de paquetes de configuración",
"Start Port":"Puerto de Empiezo",
"End Port":"Puerto de Finalizacion",
"DMZ":"DMZ",
"Enable DMZ":"Permitir DMZ",
"DMZ Address":"Direccion DMZ",
"VPN Passthrough":"VPN transferencia directa",
"IPSec passthrough":"IPSec transferencia directa",
"PPTP passthrough":"PPTP transferencia directa",
"L2TP passthrough":"L2TP transferencia directa",
"GUI Configurations":"GUI Configuraciones",
"Banner":"Pancarta",
"Display Auto Off":"Pantalla  Automática Agagado",
"SMS Font Size":"Tamaño de letra SMS",
"Custom DNS Address is empty. Please set at least one of Custom DNS":"Custom Dirección DNS está vacía. Por favor, establece al menos un DNS perzonalizado.",
"invalid External Start Address and End Address":"Dirección externa de inicio no válida y Direccion de destino",
"DMZ Address is invalid":"Direccion de DMZ ed Invalida",
"Currently data is connected. <br>Please try to disconnect the network!":"Actualmente los datos están conectados. Por favor, intente desconectar la red!",
"2G Unavailable":"2G No Disponible",
"2G Network":"Red de 2G",
"2G Available":"2G Disponible",
"4G LTE Portable Wi-Fi Hotspot":"4G LTE Portable Wi-Fi Hotspot",
" Delete ":"Borrar",
"Modify success":"modificar éxito",
"Modify failed":"Modificar falló",
"Read":"Leer",
"Received":"Recibido",
"Sent":"Enviado",
"Draft":"Borrador",
"SMS":"SMS",
"Messages":"Mensages",
"Message #":"Mensages #",
"Type":"Tipo",
"Priority":"Prioridad",
"Date":"Fecha",
"From/To":"Desde/para",
"per page":"Por pagina",
"First":"Primero",
"Prev":"Previo",
"Next":"Siguiente",
"Last":"Ultimo",
"Total number of messages":"Número total de mensages",
"Compose":"Componer",
"Delete All":"Borrar todo",
"To":"Para",
"remaining":"Restante",
"characters":"Caracteres",
"Send":"Enviar",
"Send Done":"Enviar finalizado",
"Send Fail":"Enviado sin exito",
"Contacts":"Contactos",
"Click to edit or delete":"Haga clic para editar o eliminar",
"Could not delete message.":"No se ha podido borrar el mensaje.",
"Select a message first.":"Seleccione un mensaje primero",
"There is no message.":"No hay ningún mensaje.",
"Could not read message.":"No se pudo leer el mensaje.",
"Could not get message list.":"No se pudo obtener la lista de mensajes.",
"Total number of contacts":"Número total de contactos",
"Could not modify contact":"No se pudo modificar el contacto",
"First name field is empty.":"Campo Nombre está vacío.",
"Last name field is empty.":"Campo Apellido está vacío.",
"Number field is empty.":"Número de campo está vacío.",
"Could not add contact":"No se pudo agregar el contacto",
"Could not delete all contacts.":"No se pudo borrar todos los contactos",
"Reply":"Responder",
"New Message":"Nuevo Mensage",
"Unread message":"mensaje no leído",
"Normal":"Normal",
"Interactive":"Interactivo",
"Urgent":"urgente",
"Emergency":"Emergencia",
"Do you want to delete this item":"¿Quieres eliminar este elemento",
"current":"Actual",
"bytes":"Bytes",
"First Name":"Nombre",
"Last Name":"Apellido",
"Number":"Numero",
"Message":"Mensage",
"Enter number only in Number field":"Introducir numero solamente",
"First Page":"Primera pagina",
"Prev Page":"Pagina previa",
"Next Page":"Pagina siguiente",
"Last Page":"Ultima pagina",
"Could not delete contact":"No se puede eliminar el contacto",
"Do you want to delete this message?":"Desea borrar este mensage?",
"Do you want to delete ALL messages?":"Desea borrar todos los mensages?",
"First Name or Last Name field must be entered.":"Nombre o Apellido campo debe ser ingresado.",
"Maximum number of contacts is ":"Número máximo de contactos es ",
"Could not get contact list":"No se pudo obtener la lista de contactos",
"Loading...":"Cargando...",
"From":"Desde",
"There is no contact.":"No hay ningún contacto.",
"Retry":"Reintentar",
"Dismiss":"Despedir"
}
