jquery_lang_js.prototype.lang.ko = {
"4G LTE Smart USB Modem":"4G LTE Smart USB 모뎀",
"Save":"저장",
"OK":"확인",
"Cancel":"취소",
"Saved!":"저장 완료",
"Failed!":"저장 실패",
"On":"켜짐",
"Off":"꺼짐",
"Not Activated":"활성화 안됨",
"Connecting...":"연결중...",
"Disconnecting...":"끊는중...",
"Connected":"연결됨",
"Disconnected":"연결안됨",
"No Service":"서비스 안됨",
"GSM":"GSM",
"WCDMA":"WCDMA",
"LTE":"LTE",
"Connect":"연결하기",
"Disconnect":"끊기",
"3G Unavailable":"3G 사용불가",
"3G Network":"3G 연결됨",
"3G Available":"3G 사용가능",
"4G LTE Unavailable":"4G LTE 사용불가",
"4G LTE Network":"4G LTE 연결됨",
"4G LTE Available":"4G LTE 사용가능",
"Signal:":"신호세기:",
"Device &amp; Network":"디바이스 &amp; 네트워크",
"General Device &amp; Network Information":"일반 디바이스 &amp; 네트워크 정보",
"General Device":"디바이스",
"Device Name":"장치이름",
"Device Description":"장치설명",
"Manufacturer":"제조사",
"Modem Model":"모델명",
"Hardware Version":"하드웨어 버전",
"Firmware Version":"펌웨어 버전",
"General Network":"네트워크",
"IP Address":"IP 주소",
"Gateway":"게이트웨이",
"DNS Server":"DNS 서버",
"Data Received":"수신 데이터",
"Data Sent":"송신 데이터",
"Data Total":"전체 데이터",
"4G LTE Device &amp; Network Information":"4G LTE 디바이스 &amp; 네트워크 정보",
"4G LTE Device":"디바이스",
"Technology":"기술",
"USIM State":"USIM 상태",
"4G LTE Network":"네트워크",
"Status":"상태",
"3G Device &amp; Network Information":"3G 디바이스 &amp; 네트워크 정보",
"3G Device":"디바이스",
"PRL version":"PRL 버전",
"3G Network":"네트워크",
"Check Usage":"사용내역",
" has been used":"가 사용되었습니다.",
"Jan":"1월",
"Feb":"2월",
"Mar":"3월",
"Apr":"4월",
"May":"5월",
"Jun":"6월",
"Jul":"7월",
"Aug":"8월",
"Sep":"9월",
"Oct":"10월",
"Nov":"11월",
"Dec":"12월",
"Since":"부터",
"Would you like to reset usage data?":"사용 내역을 초기화하시겠습니까?",
"Timestamp":"시간",
"Duration(total)":"기간(전체)",
"Duration(active)":"기간(활성)",
"Rx":"수신량",
"Received":"수신량",
"Tx":"송신량",
"Transmitted":"송신량",
"Total Num":"전체개수",
"Wi-Fi":"와이파이",
"Wi-Fi Profiles":"와이파이 프로파일",
"Network Name (SSID)":"네트워크 이름 (SSID)",
"802.11 Mode":"802.11 모드",
"Channel":"채널",
"Security":"보안",
"Security Option":"보안 옵션",
"WPA Passphrase":"WPA Passphrase",
"Input Type":"입력 모드",
"Connected Devices":"연결된 장치",
"Mac Address":"Mac 주소",
"Host Name":"호스트 이름",
"Expires in":"만료일",
"&nbsp;Key length is 5 ASCII characters.":"키 길이는 문자 5개입니다.",
"&nbsp;Key length is 13 ASCII characters.":"키 길이는 문자 13개입니다.",
"&nbsp;Key length is 10bytes key in hexadecimal.":"키 길이는 헥사값 10바이트입니다.",
"&nbsp;Key length is 26bytes key in hexadecimal.":"키 길이는 헥사값 26바이트입니다.",
"&nbsp;Key length is 8~63 ASCII characters.<br>&nbsp;For greater security use a mixture of digits<br>&nbsp;upper case lower case and other symbols.":"키 길이는 8~63 문자입니다. <br>보안을 강화하기 위해서 숫자 대소문자 <br>특수문자등을 섞어서 사용하십시오.",
"Rebooting your device is needed.<br>Then you need to try again to connect.<br>Do you want to continue?":"재부팅이 필요합니다.<br>재부팅후에 다시 연결해야 합니다.<br>계속 하시겠습니까?",
"Password length range is 8~63 ASCII characters.":"암호 길이는 8~63 문자입니다.",
"SSID is including invalid characters[\\]":"SSID에 유효하지 않은 문자가 포함되었습니다.",
"SSID is EMPTY":"SSID가 비었습니다",
"SSID MAX length is 32 characters":"SSID 최대 길이는 32문자입니다.",
"Password length is 10h(5c) or 26h(13c)":"암호길이는 헥사 10 혹은 26자 문자 5 혹은 13자입니다.",
"Invalid Hex Values":"유효하지 않은 헥사값입니다.",
"Password length range is 8~63 ASCII characters.":"암호 길이는 8~63자 문자입니다.",
"Invalid Security Option":"유효하지 않은 보안 옵션입니다.",
"IP Address is invalid":"IP 주소가 유효하지 않습니다.",
"Subnet Mask is invalid":"서브넷마스크가 유효하지 않습니다.",
"Start DHCP Address Range is invalid":"DHCP 주소 시작값이 유효하지 않습니다.",
"End DHCP Address Range is invalid":"DHCP 주소 끝값이 유효하지 않습니다.",
"Custom DNS Address is empty.<br>Please set at least one of Custom DNS.":"사용자 DNS 주소값이 비었습니다.<br> 최소한 하나는 설정해주십시오.",
"Custom Primary DNS Address is invalid":"사용자 Primary DNS 주소가 유효하지 않습니다.",
"Custom Secondary DNS Address is invalid":"사용자 Secondary DNS 주소가 유효하지 않습니다.",
"Settings":"설정",
"Connection Options":"연결 옵션",
"Enable Airplane Mode":"Airplane 모드 활성",
"Enable Auto Connection":"자동연결 활성",
"Automatic":"자동",
"4G LTE Only":"4G LTE만",
"3G Only":"3G만",
"LAN Setting":"LAN 설정",
"IP Address":"IP 주소",
"Subnet Mask":"서브넷마스크",
"Enable DHCP Server":"DHCP 서버 활성",
"Start DHCP Address Range":"DHCP 주소 영역 시작",
"End DHCP Address Range":"DHCP 주소  영역 끝",
"Custom DNS":"사용자 DNS 설정",
"Enable Custom DNS":"사용자 DNS 활성",
"Custom Primary DNS Address":"사용자 Primary DNS 주소",
"Custom Secondary DNS Address":"사용자 Secondary DNS 주소",
"Advanced Settings":"고급설정",
"General Settings":"일반설정",
"LED Control":"LED 제어",
"Disable LED":"LED 비활성",
"Advanced Settings Password":"관리자 암호 설정",
"Original Password(Default is admin)":"현재 암호 입력",
"New Password":"새 암호 입력",
"Confirm New Password":"새 암호 재입력",
"Password successfully changed!":"암호가 성공적으로 변경되었습니다.",
"New password not set.":"새암호가 설정되지 않았습니다.",
"Password do not match.":"암호가 일치하지 않습니다.",
"Internal error please try again.":"에러 발생. 재시도하십시오",
"You can't change the password.":"암호를 변경할수 없습니다.",
"The user name is incorrect.":"사용자 이름이 옳지 않습니다.",
"The password is incorrect.":"암호가 옳지 않습니다.",
"Manual Configuration":"사용자 설정",
"LTE Profile":"LTE 프로파일",
"WCDMA Profile":"WCDMA 프로파일",
"GSM Profile":"GSM 프로파일",
"APN name":"APN 이름",
"Authentication Preference":"보안 설정",
"Username":"사용자이름",
"Updates":"업데이트",
"Automatic Version Check":"자동 버전 체크",
"Enable notification":"알림 설정",
"Check System Upgrade":"버전 체크",
"Current Software Version":"현재 버전",
"Newest Software Version":"최신 버전",
"SW update is available. Would you like to download now?":"새로운 Software가있습니다. 다운로드 하시겠습니까?",
"No SW update available":"새로운 Software가 없습니다.",
"Check Now":"지금 확인",
"Software Update":"소프트웨어 업그레이드",
"Update software to device":"소프트웨어 다운로드",
"Engineering":"개발자 메뉴",
"System Log Settings":"로깅 설정",
"Sets the local log level of messages :":"로깅 레벨 설정 :",
"Max size (KB) before rotate(1~500) :":"로깅 사이즈(1~500) :",
"Number of rotated logs to keep(1~10) :":"로깅 파일 개수(1~10) :",
"System Logs":"로그",
"Export to Desktop":"PC에 저장",
"Refresh":"갱신",
"Clear Log":"지우기",
"Equipment":"상세 정보",
"Refurbish":"초기화",
"Factory Reset":"공장 초기화",
"Reset":"초기화",
"Debug":"디버그",
"Refresh Rate(Seconds) :":"갱신 속도(초) :",
"Common":"공통",
"Current Service":"현재 서비스",
"Signal Strength":"신호 세기",
"Roaming Indicator":"로밍 상태",
"Last Error Code":"마지막 에러코드",
"Serving Cell":"서빙 셀",
"Band":"밴드",
"State":"상태",
"UL Channel":"업로드 채널",
"DL Channel":"다운로드 채널",
"Tx Power":"Tx 파워",
"Error Rate":"에러률",
"Version":"버전",
"Help":"도움말",
"About":"정보",
"System Name":"소프트웨어 정보",
"Franklin 3G/4G Connection Manager":"Franklin 3G/4G 연결 관리자",
"CM Version":"CM 버전",
"User Guide":"매뉴얼",
"Absent":"없음",
"Present":"있음",
"Error":"에러",
"Would you like to log out now?":"로그아웃하시겠습니까? ",
"Yes":"네",
"No":"아니오",
"Administrator":"관리자",
"Log Out":"로그아웃",
"Password":"암호",
"Default password: admin":"초기암호:admin",
"MSL code required":"MSL code를 넣어주세요.",
"Sorry the MSL is incorrect.<br>Please try again.":"MSL code가 맞지 않습니다.<br> 다시 입력해주세요.",
"Administrator Login Required":"관리자 로그인이 필요합니다.",
"Your session may expired.<br>Please login again.":"세션이 종료되었습니다. <br>다시 로그인하십시오.",
"Sorry the Administrator password is incorrect.<br>Please try again.":"암호가 올바르지 않습니다.<br>다시 입력해주세요.",
"Sorry the web site is busy.<br>Please try again later.":"웹페이지가 응답하지 않습니다.<br>나중에 다시 시도해주세요.",
"Sorry there is already an online administrator.":"이미 관리자로 로그인되어 있습니다.",
"You have no authority please login as an administrator.":"권한이 없습니다. 관리자로 로그인해주십시오.",
"Sorry there is already an online user from CLI.":"이미 사용자 온라인 상태입니다.",
"Set as default":"초기값 설정",
"Edit":"편집",
"Add":"추가",
"Delete":"삭제",
"Can NOT delete a default profile!":"기본으로 설정된 프로파일은 삭제할수 없습니다.",
"Profiles":"프로파일",
"2G/3G Device &amp; Network Information":"2G/3G 디바이스 &amp; 네트워크 정보",
"2G/3G Device":"디바이스",
"2G/3G Network":"네트워크",
"2G Only":"2G만",
"2G/3G Unavailable":"2G/3G 사용불가",
"2G/3G Network":"2G/3G 연결됨",
"2G/3G Available":"2G/3G 사용가능",
"Activate":"활성",
"No Signal":"신호없음.",
"Airplane Mode":"비행기 모드",
"Network Search":"네트워크 검색",
"Automatic search":"자동 검색",
"Manual search":"수동 검색",
"Operator":"사업자",
"Network type":"네트워크 타입",
"Status":"상태",
"Available":"가능",
"Serving":"사용중",
"Unknown":"모름",
"Search":"검색",
"Select":"선택",
"Connection Options will change to '3G Only' mode.":"연결 옵션이 '3G Only' 모드로 변경됩니다.",
"Connection Options will change to '2G Only' mode.":"연결 옵션이 '2G Only' 모드로 변경됩니다.",
"Connection Options will change to '4G LTE Only' mode.":"연결 옵션이'4G LTE Only' 모드로 변경됩니다.",
"Searching...":"검색중...",
"This may take a few moments.":"몇분정도 소요됩니다."
}
