jquery_lang_js.prototype.lang.pt = {
"4G LTE Smart USB Modem":"4G LTE Smart USB Modem",
"Save":"Save",
"OK":"OK",
"Cancel":"Cancel",
"Saved!":"Saved!",
"Failed!":"Failed!",
"On":"On",
"Off":"Off",
"Not Activated":"Not Activated",
"Connecting...":"Connecting...",
"Disconnecting...":"Disconnecting...",
"Connected":"Connected",
"Disconnected":"Disconnected",
"No Service":"No Service",
"GSM":"GSM",
"WCDMA":"WCDMA",
"LTE":"LTE",
"Connect":"Connect",
"Disconnect":"Disconnect",
"3G Unavailable":"3G Unavailable",
"3G Network":"3G Network",
"3G Available":"3G Available",
"4G LTE Unavailable":"4G LTE Unavailable",
"4G LTE Network":"4G LTE Network",
"4G LTE Available":"4G LTE Available",
"Signal:":"Signal:",
"Device &amp; Network":"Device &amp; Network",
"General Device &amp; Network Information":"General Device &amp; Network Information",
"General Device":"General Device",
"Device Name":"Device Name",
"Device Description":"Device Description",
"Manufacturer":"Manufacturer",
"Modem Model":"Modem Model",
"Hardware Version":"Hardware Version",
"Firmware Version":"Firmware Version",
"General Network":"General Network",
"IP Address":"IP Address",
"Gateway":"Gateway",
"DNS Server":"DNS Server",
"Data Received":"Data Received",
"Data Sent":"Data Sent",
"Data Total":"Data Total",
"4G LTE Device &amp; Network Information":"4G LTE Device &amp; Network Information",
"4G LTE Device":"4G LTE Device",
"Technology":"Technology",
"USIM State":"USIM State",
"4G LTE Network":"4G LTE Network",
"Status":"Status",
"3G Device &amp; Network Information":"3G Device &amp; Network Information",
"3G Device":"3G Device",
"PRL version":"PRL version",
"3G Network":"3G Network",
"Check Usage":"Check Usage",
" has been used":" has been used",
"Jan":"Jan",
"Feb":"Feb",
"Mar":"Mar",
"Apr":"Apr",
"May":"May",
"Jun":"Jun",
"Jul":"Jul",
"Aug":"Aug",
"Sep":"Sep",
"Oct":"Oct",
"Nov":"Nov",
"Dec":"Dec",
"Since":"Since",
"Would you like to reset usage data?":"Would you like to reset usage data?",
"Timestamp":"Timestamp",
"Duration(total)":"Duration(total)",
"Duration(active)":"Duration(active)",
"Rx":"Rx",
"Received":"Received",
"Tx":"Tx",
"Transmitted":"Transmitted",
"Total Num":"Total Num",
"Wi-Fi":"Wi-Fi",
"Wi-Fi Profiles":"Wi-Fi Profiles",
"Network Name (SSID)":"Network Name (SSID)",
"802.11 Mode":"802.11 Mode",
"Channel":"Channel",
"Security":"Security",
"Security Option":"Security Option",
"WPA Passphrase":"WPA Passphrase",
"Input Type":"Input Type",
"Connected Devices":"Connected Devices",
"Mac Address":"Mac Address",
"Host Name":"Host Name",
"Expires in":"Expires in",
"&nbsp;Key length is 5 ASCII characters.":"&nbsp;Key length is 5 ASCII characters.",
"&nbsp;Key length is 13 ASCII characters.":"&nbsp;Key length is 13 ASCII characters.",
"&nbsp;Key length is 10bytes key in hexadecimal.":"&nbsp;Key length is 10bytes key in hexadecimal.",
"&nbsp;Key length is 26bytes key in hexadecimal.":"&nbsp;Key length is 26bytes key in hexadecimal.",
"&nbsp;Key length is 8~63 ASCII characters.<br>&nbsp;For greater security use a mixture of digits<br>&nbsp;upper case lower case and other symbols.":"&nbsp;Key length is 8~63 ASCII characters.<br>&nbsp;For greater security use a mixture of digits<br>&nbsp;upper case lower case and other symbols.",
"Rebooting your device is needed.<br>Then you need to try again to connect.<br>Do you want to continue?":"Rebooting your device is needed.<br>Then you need to try again to connect.<br>Do you want to continue?",
"Password length range is 8~63 ASCII characters.":"Password length range is 8~63 ASCII characters.",
"SSID is including invalid characters[\\]":"SSID is including invalid characters[\\]",
"SSID is EMPTY":"SSID is EMPTY",
"SSID MAX length is 32 characters":"SSID MAX length is 32 characters",
"Password length is 10h(5c) or 26h(13c)":"Password length is 10h(5c) or 26h(13c)",
"Invalid Hex Values":"Invalid Hex Values",
"Password length range is 8~63 ASCII characters.":"Password length range is 8~63 ASCII characters.",
"Invalid Security Option":"Invalid Security Option",
"IP Address is invalid":"IP Address is invalid",
"Subnet Mask is invalid":"Subnet Mask is invalid",
"Start DHCP Address Range is invalid":"Start DHCP Address Range is invalid",
"End DHCP Address Range is invalid":"End DHCP Address Range is invalid",
"Custom DNS Address is empty.<br>Please set at least one of Custom DNS.":"Custom DNS Address is empty.<br>Please set at least one of Custom DNS.",
"Custom Primary DNS Address is invalid":"Custom Primary DNS Address is invalid",
"Custom Secondary DNS Address is invalid":"Custom Secondary DNS Address is invalid",
"Settings":"Settings",
"Connection Options":"Connection Options",
"Enable Airplane Mode":"Enable Airplane Mode",
"Enable Auto Connection":"Enable Auto Connection",
"Automatic":"Automatic",
"4G LTE Only":"4G LTE Only",
"3G Only":"3G Only",
"LAN Setting":"LAN Setting",
"IP Address":"IP Address",
"Subnet Mask":"Subnet Mask",
"Enable DHCP Server":"Enable DHCP Server",
"Start DHCP Address Range":"Start DHCP Address Range",
"End DHCP Address Range":"End DHCP Address Range",
"Custom DNS":"Custom DNS",
"Enable Custom DNS":"Enable Custom DNS",
"Custom Primary DNS Address":"Custom Primary DNS Address",
"Custom Secondary DNS Address":"Custom Secondary DNS Address",
"Advanced Settings":"Advanced Settings",
"General Settings":"General Settings",
"LED Control":"LED Control",
"Disable LED":"Disable LED",
"Advanced Settings Password":"Advanced Settings Password",
"Original Password(Default is admin)":"Original Password(Default is admin)",
"New Password":"New Password",
"Confirm New Password":"Confirm New Password",
"Password successfully changed!":"Password successfully changed!",
"New password not set.":"New password not set.",
"Password do not match.":"Password do not match.",
"Internal error please try again.":"Internal error please try again.",
"You can't change the password.":"You can't change the password.",
"The user name is incorrect.":"The user name is incorrect.",
"The password is incorrect.":"The password is incorrect.",
"Manual Configuration":"Manual Configuration",
"LTE Profile":"LTE Profile",
"WCDMA Profile":"WCDMA Profile",
"GSM Profile":"GSM Profile",
"APN name":"APN name",
"Authentication Preference":"Authentication Preference",
"Username":"Username",
"Updates":"Updates",
"Automatic Version Check":"Automatic Version Check",
"Enable notification":"Enable notification",
"Check System Upgrade":"Check System Upgrade",
"Current Software Version":"Current Software Version",
"Newest Software Version":"Newest Software Version",
"SW update is available. Would you like to download now?":"SW update is available. Would you like to download now?",
"No SW update available":"No SW update available",
"Check Now":"Check Now",
"Software Update":"Software Update",
"Update software to device":"Update software to device",
"Engineering":"Engineering",
"System Log Settings":"System Log Settings",
"Sets the local log level of messages :":"Sets the local log level of messages :",
"Max size (KB) before rotate(1~500) :":"Max size (KB) before rotate(1~500) :",
"Number of rotated logs to keep(1~10) :":"Number of rotated logs to keep(1~10) :",
"System Logs":"System Logs",
"Export to Desktop":"Export to Desktop",
"Refresh":"Refresh",
"Clear Log":"Clear Log",
"Equipment":"Equipment",
"Refurbish":"Refurbish",
"Factory Reset":"Factory Reset",
"Reset":"Reset",
"Debug":"Debug",
"Refresh Rate(Seconds) :":"Refresh Rate(Seconds) :",
"Common":"Common",
"Current Service":"Current Service",
"Signal Strength":"Signal Strength",
"Roaming Indicator":"Roaming Indicator",
"Last Error Code":"Last Error Code",
"Serving Cell":"Serving Cell",
"Band":"Band",
"State":"State",
"UL Channel":"UL Channel",
"DL Channel":"DL Channel",
"Tx Power":"Tx Power",
"Error Rate":"Error Rate",
"Version":"Version",
"Help":"Help",
"About":"About",
"System Name":"System Name",
"Franklin 3G/4G Connection Manager":"Franklin 3G/4G Connection Manager",
"CM Version":"CM Version",
"User Guide":"User Guide",
"Absent":"Absent",
"Present":"Present",
"Error":"Error",
"Would you like to log out now?":"Would you like to log out now?",
"Yes":"Yes",
"No":"No",
"Administrator":"Administrator",
"Log Out":"Log Out",
"Password":"Password",
"Default password: admin":"Default password: admin",
"MSL code required":"MSL code required",
"Sorry the MSL is incorrect.<br>Please try again.":"Sorry the MSL is incorrect.<br>Please try again.",
"Administrator Login Required":"Administrator Login Required",
"Your session may expired.<br>Please login again.":"Your session may expired.<br>Please login again.",
"Sorry the Administrator password is incorrect.<br>Please try again.":"Sorry the Administrator password is incorrect.<br>Please try again.",
"Sorry the web site is busy.<br>Please try again later.":"Sorry the web site is busy.<br>Please try again later.",
"Sorry there is already an online administrator.":"Sorry there is already an online administrator.",
"You have no authority please login as an administrator.":"You have no authority please login as an administrator.",
"Sorry there is already an online user from CLI.":"Sorry there is already an online user from CLI.",
"Set as default":"Set as default	",
"Edit":"Edit",
"Add":"Add",
"Delete":"Delete",
"Can NOT delete a default profile!":"Can NOT delete a default profile!",
"Profiles":"Profiles",
"2G/3G Device &amp; Network Information":"2G/3G Device &amp; Network Information",
"2G/3G Device":"2G/3G Device",
"2G/3G Network":"2G/3G Network",
"2G Only":"2G Only",
"2G/3G Unavailable":"2G/3G Unavailable",
"2G/3G Network":"2G/3G Network",
"2G/3G Available":"2G/3G Available",
"Activate":"Activate",
"No Signal":"No Signal",
"Airplane Mode":"Airplane Mode",
"Network Search":"Network Search",
"Automatic search":"Automatic search",
"Manual search":"Manual search",
"Operator":"Operator",
"Network type":"Network type",
"Status":"Status",
"Available":"Available",
"Serving":"Serving",
"Unknown":"Unknown",
"Search":"Search",
"Select":"Select",
"Connection Options will change to '3G Only' mode.":"Connection Options will change to '3G Only' mode.",
"Connection Options will change to '2G Only' mode.":"Connection Options will change to '2G Only' mode.",
"Connection Options will change to '4G LTE Only' mode.":"Connection Options will change to '4G LTE Only' mode.",
"Searching...":"Searching...",
"This may take a few moments.":"This may take a few moments."
}
